import dotenv from 'dotenv'
dotenv.config()

export const {
  PORT,
  CORS_ORIGIN_URL,
  CORS_LOCAL_URL,
  MONGO_DATABASE,
  MONGO_USERNAME,
  MONGO_PASSWORD,
  MONGO_APP_NAME,
  MONGO_CLUSTER_URI,
  ATLAS_PROJECT_ID,
  ATLAS_CLUSTER_NAME,
  ATLAS_API_BASE_URL,
  ATLAS_API_PUBLIC_KEY,
  ATLAS_API_PRIVATE_KEY,
  SECRET_KEY,
  REFRESH_SECRET_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_SECRET_KEY,
  EMAIL_HOST,
  EMAIL_USERNAME,
  EMAIL_PASSWORD,
  EMAIL_TO
} = process.env

export const MONGO_URI = `mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}
@${MONGO_CLUSTER_URI}/?retryWrites=true&w=majority&appName=${MONGO_APP_NAME}`

export const ATLAS_CLUSTER_API_URL = `${ATLAS_API_BASE_URL}/groups/${ATLAS_PROJECT_ID}/clusters/${ATLAS_CLUSTER_NAME}`
export const ATLAS_SEARCH_INDEX_API_URL = `${ATLAS_CLUSTER_API_URL}/fts/indexes`
export const DIGEST_AUTH = `${ATLAS_API_PUBLIC_KEY}:${ATLAS_API_PRIVATE_KEY}`

export const COLLECTIONS = {
  ACCOUNTS: 'accounts'
}
